/*****************************************************************************
 * Copyright (C) 2023 Advanced Micro Devices, Inc. All rights reserved.
 ******************************************************************************
 */
#ifndef __NPCX_PIN_H__
#define __NPCX_PIN_H__

#include "gpio_ec.h"

/**
 * @brief nuvton EC generic gpio pin definitions.
 */
#define EC_GPIO_00	EC_GPIO_PORT_PIN(NUVO_GPIO_0, NUVO_GPIO_00)
#define EC_GPIO_01	EC_GPIO_PORT_PIN(NUVO_GPIO_0, NUVO_GPIO_01)
#define EC_GPIO_02	EC_GPIO_PORT_PIN(NUVO_GPIO_0, NUVO_GPIO_02)
#define EC_GPIO_03	EC_GPIO_PORT_PIN(NUVO_GPIO_0, NUVO_GPIO_03)
#define EC_GPIO_04	EC_GPIO_PORT_PIN(NUVO_GPIO_0, NUVO_GPIO_04)
#define EC_GPIO_05	EC_GPIO_PORT_PIN(NUVO_GPIO_0, NUVO_GPIO_05)
#define EC_GPIO_06	EC_GPIO_PORT_PIN(NUVO_GPIO_0, NUVO_GPIO_06)
#define EC_GPIO_07	EC_GPIO_PORT_PIN(NUVO_GPIO_0, NUVO_GPIO_07)
                                                 
#define EC_GPIO_10	EC_GPIO_PORT_PIN(NUVO_GPIO_1, NUVO_GPIO_10)
#define EC_GPIO_11	EC_GPIO_PORT_PIN(NUVO_GPIO_1, NUVO_GPIO_11)
#define EC_GPIO_12	EC_GPIO_PORT_PIN(NUVO_GPIO_1, NUVO_GPIO_12)
#define EC_GPIO_13	EC_GPIO_PORT_PIN(NUVO_GPIO_1, NUVO_GPIO_13)
#define EC_GPIO_14	EC_GPIO_PORT_PIN(NUVO_GPIO_1, NUVO_GPIO_14)
#define EC_GPIO_15	EC_GPIO_PORT_PIN(NUVO_GPIO_1, NUVO_GPIO_15)
#define EC_GPIO_16	EC_GPIO_PORT_PIN(NUVO_GPIO_1, NUVO_GPIO_16)
#define EC_GPIO_17	EC_GPIO_PORT_PIN(NUVO_GPIO_1, NUVO_GPIO_17)
                                                 
#define EC_GPIO_20	EC_GPIO_PORT_PIN(NUVO_GPIO_2, NUVO_GPIO_20)
#define EC_GPIO_21	EC_GPIO_PORT_PIN(NUVO_GPIO_2, NUVO_GPIO_21)
#define EC_GPIO_22	EC_GPIO_PORT_PIN(NUVO_GPIO_2, NUVO_GPIO_22)
#define EC_GPIO_23	EC_GPIO_PORT_PIN(NUVO_GPIO_2, NUVO_GPIO_23)
#define EC_GPIO_24	EC_GPIO_PORT_PIN(NUVO_GPIO_2, NUVO_GPIO_24)
#define EC_GPIO_25	EC_GPIO_PORT_PIN(NUVO_GPIO_2, NUVO_GPIO_25)
#define EC_GPIO_26	EC_GPIO_PORT_PIN(NUVO_GPIO_2, NUVO_GPIO_26)
#define EC_GPIO_27	EC_GPIO_PORT_PIN(NUVO_GPIO_2, NUVO_GPIO_27)
                                                 
#define EC_GPIO_30	EC_GPIO_PORT_PIN(NUVO_GPIO_3, NUVO_GPIO_30)
#define EC_GPIO_31	EC_GPIO_PORT_PIN(NUVO_GPIO_3, NUVO_GPIO_31)
#define EC_GPIO_32	EC_GPIO_PORT_PIN(NUVO_GPIO_3, NUVO_GPIO_32)
#define EC_GPIO_33	EC_GPIO_PORT_PIN(NUVO_GPIO_3, NUVO_GPIO_33)
#define EC_GPIO_34	EC_GPIO_PORT_PIN(NUVO_GPIO_3, NUVO_GPIO_34)
#define EC_GPIO_35	EC_GPIO_PORT_PIN(NUVO_GPIO_3, NUVO_GPIO_35)
#define EC_GPIO_36	EC_GPIO_PORT_PIN(NUVO_GPIO_3, NUVO_GPIO_36)
#define EC_GPIO_37	EC_GPIO_PORT_PIN(NUVO_GPIO_3, NUVO_GPIO_37) 
                                                 
#define EC_GPIO_40	EC_GPIO_PORT_PIN(NUVO_GPIO_4, NUVO_GPIO_40)
#define EC_GPIO_41	EC_GPIO_PORT_PIN(NUVO_GPIO_4, NUVO_GPIO_41)
#define EC_GPIO_42	EC_GPIO_PORT_PIN(NUVO_GPIO_4, NUVO_GPIO_42)
#define EC_GPIO_43	EC_GPIO_PORT_PIN(NUVO_GPIO_4, NUVO_GPIO_43)
#define EC_GPIO_44	EC_GPIO_PORT_PIN(NUVO_GPIO_4, NUVO_GPIO_44)
#define EC_GPIO_45	EC_GPIO_PORT_PIN(NUVO_GPIO_4, NUVO_GPIO_45)
#define EC_GPIO_46	EC_GPIO_PORT_PIN(NUVO_GPIO_4, NUVO_GPIO_46)
#define EC_GPIO_47	EC_GPIO_PORT_PIN(NUVO_GPIO_4, NUVO_GPIO_47)
                                                 
#define EC_GPIO_50	EC_GPIO_PORT_PIN(NUVO_GPIO_5, NUVO_GPIO_50)
#define EC_GPIO_51	EC_GPIO_PORT_PIN(NUVO_GPIO_5, NUVO_GPIO_51)
#define EC_GPIO_52	EC_GPIO_PORT_PIN(NUVO_GPIO_5, NUVO_GPIO_52)
#define EC_GPIO_53	EC_GPIO_PORT_PIN(NUVO_GPIO_5, NUVO_GPIO_53)
#define EC_GPIO_54	EC_GPIO_PORT_PIN(NUVO_GPIO_5, NUVO_GPIO_54)
#define EC_GPIO_55	EC_GPIO_PORT_PIN(NUVO_GPIO_5, NUVO_GPIO_55)
#define EC_GPIO_56	EC_GPIO_PORT_PIN(NUVO_GPIO_5, NUVO_GPIO_56)
#define EC_GPIO_57	EC_GPIO_PORT_PIN(NUVO_GPIO_5, NUVO_GPIO_57)
                                                 
#define EC_GPIO_60	EC_GPIO_PORT_PIN(NUVO_GPIO_6, NUVO_GPIO_60)
#define EC_GPIO_61	EC_GPIO_PORT_PIN(NUVO_GPIO_6, NUVO_GPIO_61)
#define EC_GPIO_62	EC_GPIO_PORT_PIN(NUVO_GPIO_6, NUVO_GPIO_62)
#define EC_GPIO_63	EC_GPIO_PORT_PIN(NUVO_GPIO_6, NUVO_GPIO_63)
#define EC_GPIO_64	EC_GPIO_PORT_PIN(NUVO_GPIO_6, NUVO_GPIO_64)
#define EC_GPIO_65	EC_GPIO_PORT_PIN(NUVO_GPIO_6, NUVO_GPIO_65)
#define EC_GPIO_66	EC_GPIO_PORT_PIN(NUVO_GPIO_6, NUVO_GPIO_66)
#define EC_GPIO_67	EC_GPIO_PORT_PIN(NUVO_GPIO_6, NUVO_GPIO_67)
                                                 
#define EC_GPIO_70	EC_GPIO_PORT_PIN(NUVO_GPIO_7, NUVO_GPIO_70)
#define EC_GPIO_71	EC_GPIO_PORT_PIN(NUVO_GPIO_7, NUVO_GPIO_71)
#define EC_GPIO_72	EC_GPIO_PORT_PIN(NUVO_GPIO_7, NUVO_GPIO_72)
#define EC_GPIO_73	EC_GPIO_PORT_PIN(NUVO_GPIO_7, NUVO_GPIO_73)
#define EC_GPIO_74	EC_GPIO_PORT_PIN(NUVO_GPIO_7, NUVO_GPIO_74)
#define EC_GPIO_75	EC_GPIO_PORT_PIN(NUVO_GPIO_7, NUVO_GPIO_75)
#define EC_GPIO_76	EC_GPIO_PORT_PIN(NUVO_GPIO_7, NUVO_GPIO_76)
#define EC_GPIO_77	EC_GPIO_PORT_PIN(NUVO_GPIO_7, NUVO_GPIO_77)
                                                 
#define EC_GPIO_80	EC_GPIO_PORT_PIN(NUVO_GPIO_8, NUVO_GPIO_80)
#define EC_GPIO_81	EC_GPIO_PORT_PIN(NUVO_GPIO_8, NUVO_GPIO_81)
#define EC_GPIO_82	EC_GPIO_PORT_PIN(NUVO_GPIO_8, NUVO_GPIO_82)
#define EC_GPIO_83	EC_GPIO_PORT_PIN(NUVO_GPIO_8, NUVO_GPIO_83)
#define EC_GPIO_84	EC_GPIO_PORT_PIN(NUVO_GPIO_8, NUVO_GPIO_84)
#define EC_GPIO_85	EC_GPIO_PORT_PIN(NUVO_GPIO_8, NUVO_GPIO_85)
#define EC_GPIO_86	EC_GPIO_PORT_PIN(NUVO_GPIO_8, NUVO_GPIO_86)
#define EC_GPIO_87	EC_GPIO_PORT_PIN(NUVO_GPIO_8, NUVO_GPIO_87)
                                                 
#define EC_GPIO_90	EC_GPIO_PORT_PIN(NUVO_GPIO_9, NUVO_GPIO_90)
#define EC_GPIO_91	EC_GPIO_PORT_PIN(NUVO_GPIO_9, NUVO_GPIO_91)
#define EC_GPIO_92	EC_GPIO_PORT_PIN(NUVO_GPIO_9, NUVO_GPIO_92)
#define EC_GPIO_93	EC_GPIO_PORT_PIN(NUVO_GPIO_9, NUVO_GPIO_93)
#define EC_GPIO_94	EC_GPIO_PORT_PIN(NUVO_GPIO_9, NUVO_GPIO_94)
#define EC_GPIO_95	EC_GPIO_PORT_PIN(NUVO_GPIO_9, NUVO_GPIO_95)
#define EC_GPIO_96	EC_GPIO_PORT_PIN(NUVO_GPIO_9, NUVO_GPIO_96)
#define EC_GPIO_97	EC_GPIO_PORT_PIN(NUVO_GPIO_9, NUVO_GPIO_97)
                                                 
#define EC_GPIO_A0	EC_GPIO_PORT_PIN(NUVO_GPIO_A, NUVO_GPIO_A0)
#define EC_GPIO_A1	EC_GPIO_PORT_PIN(NUVO_GPIO_A, NUVO_GPIO_A1)
#define EC_GPIO_A2	EC_GPIO_PORT_PIN(NUVO_GPIO_A, NUVO_GPIO_A2)
#define EC_GPIO_A3	EC_GPIO_PORT_PIN(NUVO_GPIO_A, NUVO_GPIO_A3)
#define EC_GPIO_A4	EC_GPIO_PORT_PIN(NUVO_GPIO_A, NUVO_GPIO_A4)
#define EC_GPIO_A5	EC_GPIO_PORT_PIN(NUVO_GPIO_A, NUVO_GPIO_A5)
#define EC_GPIO_A6	EC_GPIO_PORT_PIN(NUVO_GPIO_A, NUVO_GPIO_A6)
#define EC_GPIO_A7	EC_GPIO_PORT_PIN(NUVO_GPIO_A, NUVO_GPIO_A7)
                                                 
#define EC_GPIO_B0	EC_GPIO_PORT_PIN(NUVO_GPIO_B, NUVO_GPIO_B0)
#define EC_GPIO_B1	EC_GPIO_PORT_PIN(NUVO_GPIO_B, NUVO_GPIO_B1)
#define EC_GPIO_B2	EC_GPIO_PORT_PIN(NUVO_GPIO_B, NUVO_GPIO_B2)
#define EC_GPIO_B3	EC_GPIO_PORT_PIN(NUVO_GPIO_B, NUVO_GPIO_B3)
#define EC_GPIO_B4	EC_GPIO_PORT_PIN(NUVO_GPIO_B, NUVO_GPIO_B4)
#define EC_GPIO_B5	EC_GPIO_PORT_PIN(NUVO_GPIO_B, NUVO_GPIO_B5)
#define EC_GPIO_B6	EC_GPIO_PORT_PIN(NUVO_GPIO_B, NUVO_GPIO_B6)
#define EC_GPIO_B7	EC_GPIO_PORT_PIN(NUVO_GPIO_B, NUVO_GPIO_B7)   
                                                 
#define EC_GPIO_C0	EC_GPIO_PORT_PIN(NUVO_GPIO_C, NUVO_GPIO_C0)
#define EC_GPIO_C1	EC_GPIO_PORT_PIN(NUVO_GPIO_C, NUVO_GPIO_C1)
#define EC_GPIO_C2	EC_GPIO_PORT_PIN(NUVO_GPIO_C, NUVO_GPIO_C2)
#define EC_GPIO_C3	EC_GPIO_PORT_PIN(NUVO_GPIO_C, NUVO_GPIO_C3)
#define EC_GPIO_C4	EC_GPIO_PORT_PIN(NUVO_GPIO_C, NUVO_GPIO_C4)
#define EC_GPIO_C5	EC_GPIO_PORT_PIN(NUVO_GPIO_C, NUVO_GPIO_C5)
#define EC_GPIO_C6	EC_GPIO_PORT_PIN(NUVO_GPIO_C, NUVO_GPIO_C6)
#define EC_GPIO_C7	EC_GPIO_PORT_PIN(NUVO_GPIO_C, NUVO_GPIO_C7)
                                                 
#define EC_GPIO_D0	EC_GPIO_PORT_PIN(NUVO_GPIO_D, NUVO_GPIO_D0)
#define EC_GPIO_D1	EC_GPIO_PORT_PIN(NUVO_GPIO_D, NUVO_GPIO_D1)
#define EC_GPIO_D2	EC_GPIO_PORT_PIN(NUVO_GPIO_D, NUVO_GPIO_D2)
#define EC_GPIO_D3	EC_GPIO_PORT_PIN(NUVO_GPIO_D, NUVO_GPIO_D3)
#define EC_GPIO_D4	EC_GPIO_PORT_PIN(NUVO_GPIO_D, NUVO_GPIO_D4)
#define EC_GPIO_D5	EC_GPIO_PORT_PIN(NUVO_GPIO_D, NUVO_GPIO_D5)
#define EC_GPIO_D6	EC_GPIO_PORT_PIN(NUVO_GPIO_D, NUVO_GPIO_D6)
#define EC_GPIO_D7	EC_GPIO_PORT_PIN(NUVO_GPIO_D, NUVO_GPIO_D7)
                                                 
#define EC_GPIO_E0	EC_GPIO_PORT_PIN(NUVO_GPIO_E, NUVO_GPIO_E0)
#define EC_GPIO_E1	EC_GPIO_PORT_PIN(NUVO_GPIO_E, NUVO_GPIO_E1)
#define EC_GPIO_E2	EC_GPIO_PORT_PIN(NUVO_GPIO_E, NUVO_GPIO_E2)
#define EC_GPIO_E3	EC_GPIO_PORT_PIN(NUVO_GPIO_E, NUVO_GPIO_E3)
#define EC_GPIO_E4	EC_GPIO_PORT_PIN(NUVO_GPIO_E, NUVO_GPIO_E4)
#define EC_GPIO_E5	EC_GPIO_PORT_PIN(NUVO_GPIO_E, NUVO_GPIO_E5)
#define EC_GPIO_E6	EC_GPIO_PORT_PIN(NUVO_GPIO_E, NUVO_GPIO_E6)
#define EC_GPIO_E7	EC_GPIO_PORT_PIN(NUVO_GPIO_E, NUVO_GPIO_E7)
                                                 
#define EC_GPIO_F0	EC_GPIO_PORT_PIN(NUVO_GPIO_F, NUVO_GPIO_F0)
#define EC_GPIO_F1	EC_GPIO_PORT_PIN(NUVO_GPIO_F, NUVO_GPIO_F1)
#define EC_GPIO_F2	EC_GPIO_PORT_PIN(NUVO_GPIO_F, NUVO_GPIO_F2)
#define EC_GPIO_F3	EC_GPIO_PORT_PIN(NUVO_GPIO_F, NUVO_GPIO_F3)
#define EC_GPIO_F4	EC_GPIO_PORT_PIN(NUVO_GPIO_F, NUVO_GPIO_F4)
#define EC_GPIO_F5	EC_GPIO_PORT_PIN(NUVO_GPIO_F, NUVO_GPIO_F5)
#define EC_GPIO_F6	EC_GPIO_PORT_PIN(NUVO_GPIO_F, NUVO_GPIO_F6)
#define EC_GPIO_F7	EC_GPIO_PORT_PIN(NUVO_GPIO_F, NUVO_GPIO_F7)



#endif /* __NPCX_PIN_H__ */
