/**
* Copyright (c) 2019 Intel Corporation
* Modifications copyright (c) 2023 Advanced Micro Devices, Inc.
*/

#include <zephyr/logging/log.h>
#include "board_id.h"
#include "board_config.h"
#include "smc.h"
#include "smchost.h"
#include "smchost_commands.h"
#include "scicodes.h"
#include "sci.h"
#include "acpi.h"
#include "app_pseq.h"
#include "app_btn.h"
#include "periphmgmt.h"
#include "espi_hub.h"
#include "app_acpi.h"
#include "app_ucsi_tunnel.h"
#include "ec_debug.h"
#include "app_udc.h"
#include "task_handler.h"

LOG_MODULE_REGISTER(smchost, CONFIG_SMCHOST_LOG_LEVEL);

/* ************************** *
 *     global valuable        *
 * ************************** */
uint8_t host_req[SMCHOST_MAX_BUF_SIZE];
uint8_t host_res[SMCHOST_MAX_BUF_SIZE];
uint8_t host_req_len;
uint8_t host_res_len;
uint8_t host_res_idx;
uint8_t prev_kb_bklt_pwm_duty;

struct acpi_tbl g_acpi_tbl;

/* ************************** *
 *     static valuable        *
 * ************************** */
static bool proc_host_send(void);
static void proc_acpi_burst(void);
static uint8_t smchost_req_length(uint8_t command);
static void smchost_cmd_handler(uint8_t command);

/* PLT_RST# status */
static uint8_t pltrst_signal_sts;
/* task slp ready */
static uint8_t *task_smchostSlpReady = NULL;

#if CONFIG_SMCHOST_EVENT_DRIVEN_TASK
/* Trigger from asynchronous events generated by other EC FW modules
 * of request from host.
 */
static struct k_sem acpi_lock;

void smchost_signal_request(void)
{
	LOG_DBG("%s", __func__);
	task_status_set(task_smchostSlpReady, TASK_STASTUS_SLEEP_READY, 0);
	
	k_sem_give(&acpi_lock);
}
#endif

/**
 * @brief Detect the acpi input buffer full status, and return the acpi type.
 */
static uint8_t smchost_acpi_ibf_get(void)
{
	if (acpi_get_flag(ACPI_EC_0, ACPI_FLAG_IBF)) {
		return ESPIHUB_ACPI_PUBLIC;
	}

	if (acpi_get_flag(ACPI_EC_1, ACPI_FLAG_IBF)) {
		return ESPIHUB_ACPI_PRIVATE_0;
	}

	return MAX_ACPI_HANDLERS;
}

/**
 * @brief Handle data from io port 666h.
 */
static void smchost_acpi_handler(void)
{

#if CONFIG_SMCHOST_EVENT_DRIVEN_TASK
	smchost_signal_request();
#endif
}

/**
 * @brief Handle data from io port 668h.
 */
static void smchost_pvt0_handler(void)
{
	smchost_signal_request();
}

#ifdef EC_SLATEMODE_HALLOUT_SNSR_R
/**
 * @brief Handle slate mode sensor state changes.
 *
 * @param slatemode_sts slate mode sensor status
 */
static void smchost_slatemode_handler(uint8_t slatemode_sts)
{
	LOG_DBG("%s", __func__);

	if (g_acpi_state_flags.acpi_mode) {
		if (slatemode_sts) {
			enqueue_sci(SCI_SLATEMODE_RELEASE);
		} else {
			enqueue_sci(SCI_SLATEMODE_PRESS);
		}
	}
}
#endif

/**
 * @brief host platform reset handler
 *
 * @param pltrst_sts host platform reset status
 */
static void smchost_pltrst_handler(uint8_t pltrst_sts)
{
	LOG_DBG("PLT_RST status changed %d", pltrst_sts);
	g_acpi_state_flags.sci_enabled = pltrst_sts;
	pltrst_signal_sts = pltrst_sts;
	LOG_DBG("SCI enabled %d", g_acpi_state_flags.sci_enabled);

	/*
	 * send vw_SLAVE_BOOT_LOAD_STATUS and vw_SLAVE_BOOT_LOAD_DONE when
	 * both flash and VW channels are ready
	 */
	if (pltrst_signal_sts)
		espihub_onBothFaVwChReady();
}

/**
 * @brief host bus reset handler
 *
 * @param busrst_sts host bus reset status
 */
static void smchost_busrst_handler(uint8_t busrst_sts)
{
	LOG_DBG("BUS_RST status changed %d", busrst_sts);
	app_espi_oob_reset();
	if (busrst_sts) {
#if CONFIG_UDC_MANAGEMENT
		app_udc_refreshUdcStatus();
#endif
	} else {
		LOG_DBG("Pop ECI0 data: %x", acpi_read_idr(ACPI_EC_0));
		LOG_DBG("Pop ECI1 data: %x", acpi_read_idr(ACPI_EC_1));
		acpi_set_flag(ACPI_EC_0, 0xFF, 0);
		acpi_set_flag(ACPI_EC_1, 0xFF, 0);

	}


}

/**
 * @brief host warn reset handler
 *
 * @param host_rst_wrn_sts host warn reset status
 */
static void smchost_host_rst_warn_handler(uint8_t host_rst_wrn_sts)
{
	if (host_rst_wrn_sts) {
		g_acpi_state_flags.sci_enabled = 0;
		sci_queue_flush();
	}
}

/**
 * @brief init the smchost task
 */
static inline int smchost_task_init(void)
{
	host_req_len = 0;
	host_res_len = 0;

#if CONFIG_SMCHOST_EVENT_DRIVEN_TASK
	k_sem_init(&acpi_lock, 0, 1);
#endif

	/* Initialize flags */
	sci_queue_init();

	/* Register event handler */
	app_btn_registerHandler(smchost_pwrbtn_handler);
	espihub_add_acpi_handler(ESPIHUB_ACPI_PUBLIC, smchost_acpi_handler);
#if defined(CONFIG_ESPI_PERIPHERAL_EC_HOST_CMD) || defined(CONFIG_ESPI_PERIPHERAL_HOST_IO_PVT)
	espihub_add_acpi_handler(ESPIHUB_ACPI_PRIVATE_0, smchost_pvt0_handler);
#endif
	espihub_add_warn_handler(ESPIHUB_RESET_WARNING,
				 smchost_host_rst_warn_handler);
	espihub_add_warn_handler(ESPIHUB_PLATFORM_RESET,
				 smchost_pltrst_handler);
	espihub_add_warn_handler(ESPIHUB_BUS_RESET,
				 smchost_busrst_handler);
	
	return 0;
}

/**
 * @brief process the smchost task
 *
 * @retval True if pending data
 */
static bool smchost_process_tasks(void)
{
	bool pend_data;
	/* Check for SMI/SCI pending and service any commands
	 * from the host
	 */
	if (!acpi_get_flag(ACPI_EC_0, ACPI_FLAG_IBF) && (!acpi_get_flag(ACPI_EC_0, ACPI_FLAG_OBF))) {
		check_sci_queue();
	}
	pend_data = proc_host_send();

	return (sci_pending() || pend_data);
}

/**
 * @brief Service ACPI EC0 interface commands from host.
 */
void smchost_acpi0_service(void)
{
	while (acpi_get_flag(ACPI_EC_0, ACPI_FLAG_IBF)) {
		if (acpi_get_flag(ACPI_EC_0, ACPI_FLAG_CD)) {
			/* It is a command */
			host_req_len = 0;
	
			/* Read the command byte */
			host_req[host_req_len] = acpi_read_idr(ACPI_EC_0);
			LOG_DBG("Rcv EC cmd: %02X",
				host_req[host_req_len]);
	
		} else {
			if (host_req_len < SMCHOST_MAX_BUF_SIZE) {
				/* Read the data byte */
				host_req[host_req_len] = acpi_read_idr(ACPI_EC_0);
				LOG_DBG("Host Rcvdata[%d] = %02X",
					host_req_len, host_req[host_req_len]);
			} else {
				LOG_WRN("Exceeds Rcvdata buf size! Ignored");
				break;
			}
		}
	
		/* When a command is received check if the command corresponds
		 * to a ACPI read/write operation then ackwnowledge the OS
		 * before performing the operation.
		 */
		if (host_req[0]) {
			if (host_req[0] == EC_READ) {
				/* According to the acpi_6_3 specs */
				if (host_req_len != 1) {
					generate_sci();
				}
			}

			if (host_req[0] == EC_WRITE) {
				generate_sci();
			}
	
			if (smchost_req_length(host_req[0]) == host_req_len) {
				LOG_INF("EC Command: %02X", host_req[0]);
				smchost_cmd_handler(host_req[0]);
				host_req[0] = 0;

				/* Update SCI quickly at the end of each command handler */
				if (sci_pending()) {
					acpi_set_flag(ACPI_EC_0, ACPI_FLAG_SCIEVENT, 1);
					generate_sci();
				}
			}
		}

		host_req_len++;
	}
}

/**
 * @brief Service ACPI EC1 interface commands from host.
 */
void smchost_acpi1_service(void)
{
	uint8_t data = 0;

	while (acpi_get_flag(ACPI_EC_1, ACPI_FLAG_IBF)) {
		/* Only handle data port */
		if ( !acpi_get_flag(ACPI_EC_1, ACPI_FLAG_CD) ) {
			/* ACPI_FLAG_IBF will be cleared after acpi_read_idr */
			data = acpi_read_idr(ACPI_EC_1);
			LOG_INF("Rcv EC data from port 0x668: %02X", data);
		} else {
			/* do not process the port 66C for command */
		}

		/* process the data for UCSI */
		if (data == 0xE0) {
#if CONFIG_USBC_UCSI_TUNNEL
			app_ucsi_tunnel_hostWriteDone();
#endif
		} else if (data == 0xE1) {
#if CONFIG_USBC_UCSI_TUNNEL
			app_ucsi_tunnel_hostReadDone();
#endif
		}
		/* process the data for eSPI FA test */
		if (espihub_get_saf_boot_mode() == false) {
			extern void app_espi_fa_testTrigger(uint8_t ops);
			extern void app_spiS0_quickTestWrapper(uint8_t testCase);
			if (data == 0xD0) { // eSPI FA read  = APP_ESPI_FLASH_READ
				app_espi_fa_testTrigger(0);
			} else if (data == 0xD1) { // eSPI FA write = APP_ESPI_FLASH_WRITE
				app_espi_fa_testTrigger(1);
			} else if (data == 0xD2) { // eSPI FA ERASE = APP_ESPI_FLASH_ERASE_SMALLER
				app_espi_fa_testTrigger(2);
			} else if (data == 0xDC) { // RCIN# assert
				espihub_send_vw(ESPI_VWIRE_SIGNAL_RST_CPU_INIT, ESPIHUB_VW_LOW);
			} else if (data == 0xDE) { // FA stress EN
				app_spiS0_quickTestWrapper(1);
			} else if (data == 0xDD) { // FA stress Disable
				app_spiS0_quickTestWrapper(0);
			} else if (data == 0xBB) { // SPI banchmark 120KB
				app_spiS0_quickTestWrapper(2);
			} else if (data == 0xBE) { // SPI banchmark 500KB
				app_spiS0_quickTestWrapper(3);
			} else if (data == 0xF0) { // _spiS0_fillRom 0
				app_spiS0_quickTestWrapper(4);
			} else if (data == 0xFF) { // _spiS0_fillRom 0xFF
				app_spiS0_quickTestWrapper(5);
			} else if (data == 0xFC) { // _spiS0_fillRom 0xCC
				app_spiS0_quickTestWrapper(6);
			} else if (data == 0x72) { // _spiS0_fillRom 0x72, fill the test region by
						   // u_misc_pr_genRandArray
				app_spiS0_quickTestWrapper(7);
			}
		}
	}
}

/**
 * @brief Send byte to OSPM via ACPI interface.
 *
 * @param acpi_num ACPI EC interface number
 * @param byte data byte to send
 * @retval 0 on success, non-zero on failure
 */
static int acpi_to_ospm(enum acpi_ec_interface acpi_num, uint8_t byte)
{
	if (sci_pending()) {
		acpi_set_flag(acpi_num, ACPI_FLAG_SCIEVENT, 1);
	} else {
		acpi_set_flag(acpi_num, ACPI_FLAG_SCIEVENT, 0);
	}

	int ret = acpi_send_byte(acpi_num, byte);
	
	if (ret == 0) {
		generate_sci();
	}

	return ret;
}

/**
 * @brief SMC host management.
 *
 * This routine handles all commands received from BIOS in ACPI mode.
 *
 * @param p1 pointer to additional task-specific data.
 * @param p2 pointer to additional task-specific data.
 * @param p3 pointer to additional task-specific data.
 */
void smchost_thread(void *p1, void *p2, void *p3)
{
#if CONFIG_SMCHOST_EVENT_DRIVEN_TASK
	bool pend_processing;
#endif
	task_smchostSlpReady = (uint8_t *)p2;
	smchost_task_init();
	/* Can enter sleep before first circle */
	task_status_set(task_smchostSlpReady, TASK_STASTUS_SLEEP_READY, 1);
	
#if CONFIG_SMCHOST_EVENT_DRIVEN_TASK
	while (true) {
		k_sem_take(&acpi_lock, K_FOREVER);
		LOG_DBG("%s process", __func__);


		bool acpi_run = false;
		while(smchost_acpi_ibf_get() < MAX_ACPI_HANDLERS) {
			smchost_acpi0_service();
			smchost_acpi1_service();
			acpi_run = true;
		};

		if (acpi_run) {
		    acpi_ibf_intr(ACPI_EC_0, 1);
		    acpi_ibf_intr(ACPI_EC_1, 1);
		}

		/* 1) Process all smchost actions triggered by event
		 * 2) Repeat until there is no activity related to same event
		 * 3) Go back to wait for next event.
		 */
		pend_processing = smchost_process_tasks();

		/* Perform delay only in SCI pending notification */
		if (!pend_processing) {
			task_status_set(task_smchostSlpReady, TASK_STASTUS_SLEEP_READY, 1);
		}
		    acpi_ibf_intr(ACPI_EC_0, 1);
		    acpi_ibf_intr(ACPI_EC_1, 1);
	}
#else
	while (true) {
		/* Process tasks periodically*/
		smchost_process_tasks();
		k_msleep(period);
	}
#endif
}

/**
 * @brief process the host send message
 *
 * @retval true if data pending, false otherwise
 */
static bool proc_host_send(void)
{
	if (host_res_len > 0) {
		uint8_t flag = acpi_get_flag(ACPI_EC_0, ACPI_FLAG_OBF);

		LOG_DBG("ACPI OBF flag %x", flag);
		if (!flag) {
			LOG_DBG("WriteODR %x",  host_res[host_res_idx]);
			acpi_write_odr(ACPI_EC_0, host_res[host_res_idx]);
			host_res_idx++;
			host_res_len--;
		}
	}

	return (host_res_len > 0);
}

/**
 * @brief Send data to the host.
 *
 * @param pdata pointer to the data.
 * @param Len data length in bytes.
 */
void send_to_host(uint8_t *pdata, uint8_t Len)
{
	int i;

	for (i = 0; i < Len; i++) {
		host_res[i] = *(pdata + i);
		LOG_DBG("Snd data: %02X",  host_res[i]);
	}

	host_res_len = Len;
	host_res_idx = 0;
}

/**
 * @brief check if it is unsupport command
 *
 * @param command the unsupported command code
 */
void host_cmd_default(uint8_t command)
{
	/* Log the execution to know BIOS send an unsupported command */
	LOG_WRN("%s: command 0x%X without handler", __func__, command);
}

/**
 * @brief ACPI read to ECRAM
 */
static void acpi_read_ec(void)
{
	uint8_t acpi_idx = host_req[1];
	uint8_t data = 0xFF;

	if (acpi_idx <= ACPI_MAX_INDEX) {
#ifdef ACPIPLANES_SUPPORTED
		md_acpiplanes_dispatcher(1, acpi_idx, &data);
#else
		data = *((uint8_t *)&g_acpi_tbl + acpi_idx);
#endif
		LOG_DBG("ACPI ECR Data [%02x]: %02x", acpi_idx, data);
	} else {
		data = acpi_idx;
	}

	if (acpi_to_ospm(ACPI_EC_0, data) != 0) {
		LOG_ERR("ACPI Write Date failed");
	}

}

/**
 * @brief ACPI write to ECRAM
 */
static void acpi_write_ec(void)
{
	uint8_t acpi_idx = host_req[1];
	uint8_t data = host_req[2];

	if (acpi_idx <= ACPI_MAX_INDEX) {
#ifdef ACPIPLANES_SUPPORTED
		md_acpiplanes_dispatcher(0, acpi_idx, &data);
		LOG_DBG("ACPI ECW Data [%02x]: %02x", acpi_idx, data);
#else
		if (smc_is_acpi_offset_write_permitted(acpi_idx)) {
			*((uint8_t *)&g_acpi_tbl + acpi_idx) = data;
			LOG_DBG("ACPI ECW Data [%02x]: %02x", acpi_idx, data);
		} else {
			LOG_WRN("ACPI WR not permitted at offset: %02x",
				acpi_idx);
		}
#endif
	}

}

/**
 * @brief get the LPT reset signal status
 *
 * @retval signal status
 */
uint8_t get_pltrst_signal_sts(void)
{
	return pltrst_signal_sts;
}

#if CONFIG_THERMAL_MANAGEMENT
/**
 * @brief Change PECI access mode based on host request.
 */
static void change_peci_access_mode(void)
{
#ifndef CONFIG_DEPRECATED_HW_STRAP_BASED_PECI_MODE_SEL
	LOG_DBG("%s:Host peci_mode : %x", __func__, host_req[1]);
	peci_access_mode_config(host_req[1]);
#endif /* CONFIG_DEPRECATED_HW_STRAP_BASED_PECI_MODE_SEL */
}
#endif

/**
 * @brief set the burst EC flag
 */
static void acpi_burst_ec(void)
{
	proc_acpi_burst();
}

/**
 * @brief process the ACPI brust
 */
static void proc_acpi_burst(void)
{
	/* Tell host that we're burst */
	acpi_set_flag(ACPI_EC_0, ACPI_FLAG_ACPIBURST, 1);
	if (acpi_to_ospm(ACPI_EC_0, SCI_BURST_ACK) != 0) {
		LOG_ERR("Burst ACK failed");
	}

	/* Abort burst */
	acpi_set_flag(ACPI_EC_0, ACPI_FLAG_ACPIBURST, 0);
	generate_sci();
}

/**
 * @brief set ACPI normal EC flag
 */
static void acpi_normal_ec(void)
{
	acpi_set_flag(ACPI_EC_0, ACPI_FLAG_ACPIBURST, 0);
	generate_sci();
}

/**
 * @brief send the SCI event
 */
static void acpi_query_ec(void)
{
	/* Send any pending events */
	send_sci_events();
}

/**
 * @brief return the required data length for different ACPI command
 *
 * @param command ACPI command
 * @retval length
 */
static uint8_t smchost_req_length(uint8_t command)
{
	switch (command) {
	case SMCHOST_PLN_CONFIG:
	case SMCHOST_CS_LOW_PWR_MODE_SET:
	case SMCHOST_ACPI_READ:
	case SMCHOST_READ_ACPI_SPACE:
	case SMCHOST_HID_BTN_SCI_CONTROL:
#if CONFIG_THERMAL_MANAGEMENT
	case SMCHOST_BIOS_FAN_CONTROL:
	case SMCHOST_SET_SHDWN_THRESHOLD:
#endif
		return 1;

	case SMCHOST_ACPI_WRITE:
	case SMCHOST_WRITE_ACPI_SPACE:
		return 2;

	default:
		return 0;
	}
}

/**
 * @brief ACPI port 666/662 command handler
 *
 * @param command ACPI command
 */
static void smchost_cmd_handler(uint8_t command)
{
	switch (command) {

	/* Handlers for commands 80h to 8Fh */
	case SMCHOST_ACPI_READ:
		acpi_read_ec();
		break;
	case SMCHOST_ACPI_WRITE:
		acpi_write_ec();
		break;
	case SMCHOST_ACPI_BURST_MODE:
		acpi_burst_ec();
		break;
	case SMCHOST_ACPI_NORMAL_MODE:
		acpi_normal_ec();
		break;
	case SMCHOST_ACPI_QUERY:
		acpi_query_ec();
		break;
	case SMCHOST_UCSI_WRITE_DONE:
#if CONFIG_USBC_UCSI_TUNNEL
		app_ucsi_tunnel_hostWriteDone();
#endif
		break;
	case SMCHOST_UCSI_READ_DONE:
#if CONFIG_USBC_UCSI_TUNNEL
		app_ucsi_tunnel_hostReadDone();
#endif
		break;
	case SMCHOST_ACPI_HOST_ENABLE:
		ACPI_EnableHostNotify();
		break;
	case SMCHOST_ACPI_HOST_DISABLE:
		ACPI_DisableHostNotify();
		break;
	default:
		host_cmd_default(command);
		break;
	}
}