/*
 * Copyright (c) 2026 Realtek Semiconductor Corporation, SIBG-SD7
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Empty stub for the IO-expander pin table that AMD's autogen
 * (scripts/ioexpTable_AutoGen.pl driven by Plum_ioexp.csv) produces
 * for Plum NPCX4. The RTS5918 version is regenerated by the same
 * tool when the Plum-on-RTS5918 expander wiring is captured; until
 * then leave the table empty so the build links.
 *
 * TODO(realtek-schematic): regenerate with Plum I2C bus assignments.
 */

#ifndef __BOARD_IOEXP_TABLE_H__
#define __BOARD_IOEXP_TABLE_H__

#endif /* __BOARD_IOEXP_TABLE_H__ */
